### ISSUE TITLE
building for arm64

### ISSUE THREAD

**Issue by davephillips** [Dewb/monome-rack#107]
MacOS Monterey 12.2
Rack 2.x local build for native arm64 (Mac Mini M1)

Just a quick note that on Linux and the Mac the build will fail until this line is added to the firmware/*.mk files:

`RACK_DIR ?= ../../..` 

The source code for VCV Rack is located at $HOME/src/Rack2.

On to testing the new build. As always, thanks for the wonderful modules !

Edit: Unfortunately it's crashing Rack on opening:

```
[1.345 info src/plugin.cpp:137 loadPlugin] Loading plugin from /Users/davephillips/src/Rack-2.2-native/plugins/monome-rack
Binding to port 13000.
Assertion failed: (sizeof(osc::int32) == 4), function OutboundPacketStream, file OscOutboundPacketStream.cpp, line 166.
make: *** [run] Abort trap: 6
```

The problem appears to be in the oscpack stuff. Any suggestions or should I leave off for a while ?

Edit: I applied this patch to oscpack:

https://github.com/yoggy/homebrew-tap/blob/master/oscpack-arm64.patch

and the plugin now loads and shows in the Browser. I'll run some tests later this evening.

Best regards,

dp

**Comment by Dewb** [comment]
Thanks for the report, and thanks for testing the brand new arm64 build! I've pushed fixes for both the implicit RACK_DIR in firmware makefiles and the oscpack x64 macros.
