### ISSUE TITLE
2.0.1-beta-mac crash on any module load 

### ISSUE THREAD

**Issue by vadimchirkov** [Dewb/monome-rack#110]
2.0.1-beta-mac-x64.vcvplugin with the latest Rack on Catalina. 
2.0.1-alpha works as expected

**Comment by Dewb** [comment]
Thanks for the report. Does this build resolve the issue? https://github.com/Dewb/monome-rack/suites/10322913437/artifacts/507958617

**Comment by vadimchirkov** [comment]
Yes. Resolved now with this build. Thank you 🙏
