### ISSUE TITLE
build fail, path issue ?

### ISSUE THREAD

**Issue by davephillips** [Dewb/monome-rack#111]
MacOS Monterey 12.2
local build Rack 2.x
monome-rack commit 6a3bdfa

Source code fails to compile:

```
% make    
cd firmware && /Library/Developer/CommandLineTools/usr/bin/make -f whitewhale.mk
common.mk:18: ../../arch.mk: No such file or directory
common.mk:35: ../../compile.mk: No such file or directory
make[1]: *** No rule to make target `../../compile.mk'.  Stop.
make: *** [firmwares] Error 2
```

Is the path to RACK_DIR getting confused somewhere ? I've tried resetting it various ways, it fails every time. Any suggestions ? Am I missing something ?

dp

**Comment by Dewb** [comment]
Sorry about that, I always provide an explicit, absolute RACK_DIR to the build environment, so I haven't been testing relative or default paths. I think https://github.com/Dewb/monome-rack/commit/dfe55e53e2f04c5a69411eb1ec30ebb235473102 should resolve the issue, let me know if that works.

**Comment by davephillips** [comment]
Thanks a lot, Michael, you nailed it. No problem with the build or the browser, on to testing the new stuff. :)

**Comment by Dewb** [comment]
Great. Thanks for testing!
