### ISSUE TITLE
All modules not working on Mac OSX Mojave

### ISSUE THREAD

**Issue by eatsleeping** [Dewb/monome-rack#121]
### If you're having trouble building, please paste the output of these commands:
   ```
   git status
   git submodule status
   make clean
   make
   ```

### If you have a patch file that reproduces the issue, please drag-and-drop it here:
[monome_blank.vcv.zip](https://github.com/Dewb/monome-rack/files/10433640/monome_blank.vcv.zip)

**Comment by Dewb** [comment]
Is this with a [released version](https://github.com/Dewb/monome-rack/releases) or with a local build? Which build/commit?

**Comment by Dewb** [comment]
Can you share your logfile (at `~/Documents/Rack2/log.txt`)?

**Comment by eatsleeping** [comment]
sure
[log.txt](https://github.com/Dewb/monome-rack/files/10441176/log.txt)

**Comment by eatsleeping** [comment]
here is a screen of what teletype looks like, there is nothing in the put screen.

![monome_sshot](https://user-images.githubusercontent.com/100716346/213063198-0ab4063e-1ef8-42cd-ba13-e8a8ba6851f7.jpg)

**Comment by Dewb** [comment]
It looks like an error in the firmware Makefiles briefly caused the firmware .dylibs to be built against a higher minimum MacOS SDK version. If that's the issue, I think it's already been fixed; can you try this build to see if it resolves the issue? https://github.com/Dewb/monome-rack/actions/runs/3936124282

**Comment by eatsleeping** [comment]
everything now seems to appear, and lights flash, haven't tested coding etc with it though yet.


![monome_sshot2](https://user-images.githubusercontent.com/100716346/213138039-16d4e1e5-fe52-4a09-bc1a-fbdfcf1caa19.jpg)

**Comment by Dewb** [comment]
Great, looks like that was it then
