### ISSUE TITLE
[BUG REPORT] Teletype starting up with blank or glitched screen

### ISSUE THREAD

**Issue by gazzar** [Dewb/monome-rack#127]
** Platform/Version **
 - OS version: Windows 11 Home 22H2
 - Rack version: Pro 2.2.3
 - Plugin version: 2.0.2-beta-win (Also tried 2.0.1-beta-win)

**Describe the bug**
In Teletype, the text-entry window contents are mangled. Expected to see a readable shell prompt.

**VCV Rack logfile**
[log_for_monome.txt](https://github.com/Dewb/monome-rack/files/10832821/log_for_monome.txt)

**How to Reproduce**
1. Load the Teletype module in Rack

**Additional context**
My Windows laptop contains an Nvidia GPU. I switched Rack between using the Intel GPU and the Nvidia GPU, and saw no difference in behaviour.

Note that the version of Teletype has not changed between 2.0.1-beta and 2.0.2-beta, but the display behaviour differs between these versions:

A couple of examples with release 2.0.2-beta-win on Win11:
![image](https://user-images.githubusercontent.com/131836/221389222-9e65b21b-1981-41eb-8759-055951aef788.png)
![image](https://user-images.githubusercontent.com/131836/221389225-6ed1da37-bcce-457e-aa23-532523d2d481.png)

With release 2.0.1-beta-win, the window is always black:
![image](https://user-images.githubusercontent.com/131836/221389306-f1bd85e1-02cb-48c0-8cb7-d685fdb3781b.png)

**Comment by Dewb** [comment]
Hi, thanks very much for the detailed report! We haven’t had much testing on Windows 11 yet. 

I don’t see any teletype module events in the log file you included, are you certain it’s from a session with teletype?

**Comment by gazzar** [comment]
Sorry about that. I must have rerun VCV after removing teletype. Here's a hopefully more informative log:
[log_for_monome2.txt](https://github.com/Dewb/monome-rack/files/10832982/log_for_monome2.txt)

**Comment by Dewb** [comment]
Thanks! No immediate clues in that file, Teletype loads without any error messages. This sort of issue generally happens when the firmware DLL is corrupted or unloadable somehow; can you remove the monome plugin directory and try re-installing again (by placing the .vcvplugin in the plugins folder, don't try to unzip the files yourself.)

**Comment by gazzar** [comment]
That was how I was uninstalling/reinstalling and how I was able to try out the previous package version; I haven't unzipped the plugin myself. Maybe this problem is isolated to my system and others running Win11 might let you know that they aren't experiencing this problem, so you might decide to wait for more corroborating reports.

**Comment by manli0** [comment]
I'm currently experiencing the same issue on a Win10 machine. I installed by copying the .vcvplugin in the plugins folder.

I wasn't able to replicate the problem on my second Win10 machine, where the plugin runs smoothly.

**Comment by Dewb** [comment]
Thanks! Can you both look at the Explorer properties of res/firmware/teletype.dll and see if it says “This file came from another computer and might be blocked to help to text this computer”? (More details: https://nolongerset.com/mark-of-the-web-details/)

**Comment by gazzar** [comment]
In my case, while I can see the security message in the original monome-2.0.2-beta-win-x64.vcvplugin file properties, it has been removed cleanly and is not in the teletype.dll file properties:
![image](https://user-images.githubusercontent.com/131836/221794576-9c37ee99-cba4-445f-a06c-4cb8a4855f7e.png)

**Comment by Dewb** [comment]
Another thing to try: right-click Teletype and choose `Preset > TRIANGLE MOUNTAIN`. Does TR 1 start blinking?

**Comment by gazzar** [comment]
> Do you have an Audio Output module with an output device selected? Are other modules in the patch running as expected? Rack used to have an issue where the audio engine would not run and modules would be frozen until an output module was placed in the patch and activated. I believe that's been addressed, but it's worth checking.

That's it (in my case)! I guess it's obvious in hindsight that I should have selected an audio output. As soon as i did that Teletype sprang to life.
So, it was a chicken-and-egg situation, where I had started with a clean slate, which meant I was thinking there's no point even starting to learn Teletype in a fresh rack if I can't get it to respond, so I hadn't even selected an audio output. Thank you Michael!

**Comment by Dewb** [comment]
Great! The glitched screen is an old issue that I inadvertently reintroduced, that should be fixed now. I'll look at adding a message so it's a little more obvious you need to get the engine running before any modules will activate.

@manli0 does connecting to an audio output resolve your problem also?

**Comment by manli0** [comment]
Sorry for the late reply, I was offline for a couple of days and missed your answers.
In the meantime the problem seemed to have gone away by itself, after testing I can now confirm it was caused by the same issue as gazzar's (no active output module). Silly mistake but I'm glad there's at least two of us 😄 

Thank you very much for your support and replies!

**Comment by Dewb** [comment]
Great, glad to hear it! The next release will have a message to make this situation less confusing (implemented in a739b32e1b8c1a588f9c4edc498df68216161010).
