### ISSUE TITLE
[BUG REPORT] Ansible and Meadowphysics crash VCV Rack 2.2.3 in Linux (EndeavourOS)

### ISSUE THREAD

**Issue by justinbloomfield** [Dewb/monome-rack#129]
**Platform/Version**
 - OS version: Linux (EndeavourOS)
 - Rack version: 2.2.3
 - Plugin version: All versions, using 2.0.2-beta but have tried previous builds

**Describe the issue**
Attempting to add either the Meadowphysics or Ansible modules into VCV Rack causes the program to crash.
Adding Ansible immediately crashes the program, without even showing the module being added, it freezes on the module selection screen for a half second then closes.
Adding Meadowphysics adds the module, but freezes immediately after and then closes. The yellow light is lit, if that's helpful. 

**Log file**
[meadowphysics log.txt](https://github.com/Dewb/monome-rack/files/10846891/meadowphysics_log.txt)
[ansible log.txt](https://github.com/Dewb/monome-rack/files/10846906/log.txt)

**How to Reproduce**
1. Open module selection screen
2. Click on ansible/meadowphysics
3. VCV Rack crashes

**Additional context**
Have tried with both modules and VCV rack built from source and binary installations, no luck.

**Comment by Dewb** [comment]
Thanks for the report! This looks like a different callstack than #78. 

Linux builds have gotten relatively less beta testing than macOS/Windows, and non-Debian-based distros are a small fraction of those users, so things might be spotty until we get more of a linux userbase or I have time to work out a virtualization-based testing environment.

**Comment by Dewb** [comment]
I believe I've fixed the Ansible crash in #78. I can't reproduce this meadowphysics crash on Ubuntu 20. You can build from head or try [this build](https://github.com/Dewb/monome-rack/actions/runs/4339366508) to see if it has any effect on your issue. Do you know where I could get test VM images of EndeavourOS? Are you handy with gdb and want to see if you can learn anything more about the crashes on your system?

**Comment by Dewb** [comment]
When I get a chance I'll try to reproduce on [an Arch image ](https://www.osboxes.org/arch-linux/).

**Comment by justinbloomfield** [comment]
Yes, it's Arch-based so hopefully that image is useful. 
No luck with building from head or with your linked build, I'm afraid, same issues. 
I haven't spent much time with gdb but if you have the time to point me in the right direction I can give it a go.

**Comment by Dewb** [comment]
I was able to reproduce on Arch, should have a fix soon!
