### ISSUE TITLE
(very minor!) unexpected Earthsea *shape* knob behavior

### ISSUE THREAD

**Issue by dndrks** [Dewb/monome-rack#150]
**Platform/Version**
 - OS version: macOS 13.1 Ventura
 - Rack version: 2.3.0 x64
 - Plugin version: 2.0.3 beta

**Describe the bug**
When instantiating an Earthsea module, the _shape_ knobs all initialize at 5V, but the actual `SHAPE x output` voltage for each channel is 0.001V and the on-grid display shows no voltage applied. When turning clockwise, I need to pass 5.1V in order to register any change. When turning counter-clockwise, I need to pass ~4.86V. Either will cause an sudden jump in outgoing voltage as well as on the on-grid display.

As a user:
- I want the knobs and voltages to all initialize at their minimum value
- I expect the 0V knob position to output 0V (shows 0.001V when inspected)
- I expect the 5V knob position to output 5V (shows 4.998V when inspected)

**VCV Rack logfile**
[log.txt](https://github.com/Dewb/monome-rack/files/11179758/log.txt)

**How to Reproduce**
1. Instantiate an Earthsea and attach it to a grid
2. Hover over any of the _shape_ knobs and the popup will say `SHAPE x: 5V`
3. The on-grid display shows no voltage is applied to any channel, however
4. Patching any of the _shape_ CV outputs and hovering over will show 0.001V
5. When any _shape_ knob is adjusted past 5.1V clockwise or ~4.86V counter-clockwise, voltage and on-grid display will jump to that value

**Additional context**
Thank you for all of the incredible work on these, holy moly!!

**Comment by Dewb** [comment]
This has come up before and as far as I can tell this is accurately reproducing hardware behavior. https://github.com/Dewb/monome-rack/issues/25

Unfortunately it is extra confusing in the software environment. I originally decided not to do anything about this, but it’s worth revisiting; doing something as simple as making sure the initial knob and preset states match up would probably reduce confusion.

**Comment by Dewb** [comment]
Thinking about this some more, I don’t think it would be hard to init knobs to the preset output state instead of their saved param values (as suggested in #25.)

**Comment by dndrks** [comment]
oh rad, yeah that makes a ton of sense -- i had totally forgotten the hardware behavior.
anything to save you from having to repeat this reasoning again and again 😅  -- the simple solution sounds totally good for this case!
