### ISSUE TITLE
Release on VCV Rack package manager

### ISSUE THREAD

**Issue by Dewb** [Dewb/monome-rack#17]
(After all other version 1 issues/features are complete)

Package manager details:
https://github.com/VCVRack/community
https://github.com/VCVRack/Rack/issues/444

Still need to determine if the package should have "monome" in the name or not.
https://llllllll.co/t/white-whale-in-vcvrack/10337/9

**Comment by Dtard** [comment]
Current Library build is giving me code 127 error.

**Comment by Dewb** [comment]
This plug-in requires Rack 2.3.0; are you on an earlier version? See [this thread](https://community.vcvrack.com/t/monome-2-1-3-update/20058). If that isn’t the issue and you’re still getting an error, please file a new issue with all the requested info about your setup, logs, etc.
