### ISSUE TITLE
[BUG REPORT] Firmware load fails on UTF-8 paths on Windows

### ISSUE THREAD

**Issue by jo1nGF** [Dewb/monome-rack#172]
** Platform/Version **
 - OS version: Windows 10
 - Rack version: 2.4.0
 - Plugin version: 2.1.5

**Describe the bug**
When inserting the monome modules in the rack, no LED lights up, no signal is sent. And the following message appears on the teletype display "vcv rack engine not active try adding an audio output"

https://scontent.ffec10-1.fna.fbcdn.net/v/t39.30808-6/366626112_10233514553984345_7527642905206278039_n.jpg?_nc_cat=102&ccb=1-7&_nc_sid=5cd70e&_nc_ohc=1nVjAGyurgAAX82FOZc&_nc_ht=scontent.ffec10-1.fna&oh=00_AfA48hL_GmXLUP8RT4aaiUpUrHWIKTMV01nYeixNwiKZoA&oe=64E7842F

**VCV Rack logfile**
Attach `log.txt` from your VCV Rack user folder ([Where is the VCV Rack user folder?](https://vcvrack.com/manual/FAQ#Where-is-the-Rack-user-folder)) log files attached just below

**How to Reproduce**
Just add Monome modules in rack and nothings working and the menssage  on teletype display

**Patch file**
[If the steps to reproduce require a particular arrangement of several modules, please attach a VCV Rack patch that demonstrates the issue.](https://drive.google.com/file/d/1gu6hPzkxBO7_uJKWQRvSQbLoY8OSzKdq/view?usp=sharing)

**Additional context**
[log.txt](https://github.com/Dewb/monome-rack/files/12388847/log.txt)

[log.txt](https://github.com/Dewb/monome-rack/files/12388876/log.txt)
![369055724_10233521510038242_3956342379072003644_n](https://github.com/Dewb/monome-rack/assets/121872330/79543698-a240-4d57-8032-d9efc135b5f5)
![image](https://github.com/Dewb/monome-rack/assets/121872330/1b9fd152-27e6-4571-9961-6c609254603b)

**Comment by Dewb** [comment]
Thanks for the report. It looks like your user home folder has Unicode in the path. The Rack log is mangling the pathname (see below), can you share what the folder should be named? It seems likely that either Rack or the plug-in is not handling the path correctly and the Teletype firmware is not loading. 

```[20.366 warn src/common/core/FirmwareManager.cpp:193 load] Failed to load library C:/Users/JoÃ£o/Documents/Rack2/plugins-win-x64/monome/res/firmware/teletype.dll: 126```

**Comment by jo1nGF** [comment]
Thanks for the quick support, the name would be " João "

**Comment by jo1nGF** [comment]
![image](https://github.com/Dewb/monome-rack/assets/121872330/ab5a0d44-aa67-4585-b9ca-8ed748aede69)

I created a folder with the module files in this path and it worked as it should, thanks to your feedback, thank you very much

**Comment by Dewb** [comment]
Great! I will look into addressing this in a future update!

**Comment by jo1nGF** [comment]
yes sir, congratulations for the excellent work.
