### ISSUE TITLE
white whale: crash when switching to CV A page in Curve mode 

### ISSUE THREAD

**Issue by midiguru23** [Dewb/monome-rack#180]
Windows 10 64-bit, VCV Pro 2.4.1, white whale/grid 128 version 2.1.5

Somehow I've gotten these two modules (one or the other) into a state where clicking on any of the CV 1 buttons in the top row causes VCV to crash.

Load my whale_crash.vcv file. Then click on any of the CV 1 buttons in the top row of the grid. (Other buttons may cause the same problem.

[log.txt](https://github.com/Dewb/monome-rack/files/12704195/log.txt)
[whale_crash.zip](https://github.com/Dewb/monome-rack/files/12704213/whale_crash.zip)

**Comment by Dewb** [comment]
Thanks for the report, looks like this is a 9+ year old issue in the while whale firmware code (that might only be an issue on x86.) The next release has already been submitted to the library but I'll try to get the fix in before it goes live.

**Comment by Dewb** [comment]
Can you try the 2.2.1 release and see if it fixes the issue for you? https://github.com/Dewb/monome-rack/releases/tag/v2.2.1

**Comment by Dewb** [comment]
FYI if you’re using CV A as a V/oct signal, in Curve mode it’s arbitrary 0-10V, in Map mode it follows semitones along a smaller range, much more useful for V/oct. To swap modes, ctrl-click to hold the Alt grid key and then click in either the CV A or B zones to toggle the mode for that channel.
