### ISSUE TITLE
[BUG REPORT] Unintended Default Faderbank Voltage Range?

### ISSUE THREAD

**Issue by VegaDeftwing** [Dewb/monome-rack#184]
** Platform/Version **
 - OS version: Win11
 - Rack version: Pro 2.4.1
 - Plugin version: 2.2.2

**Describe the bug**
The fader voltage range defaults to 0-10V in the right-click menu, but actually outputs +/-10V. If you change it to any other mode and then select 0-10V, it's actually 0-10V, making it impossible to return to the +/-10V mode it's in by default.

**Comment by VegaDeftwing** [comment]
Bug seems to be from https://github.com/Dewb/monome-rack/blob/f5efa815fcdbe1bbb0909a27b4a473bd6c49e34c/src/faderbank/FaderbankModule.cpp#L10 setting the range to +/-10 but then not calling `FaderbankModule::updateFaderRanges()` on load?

**Comment by Dewb** [comment]
Thanks for writing this up, I noticed this yesterday as well.

**Comment by Dewb** [comment]
Fixed in 2.2.3: https://github.com/Dewb/monome-rack/releases
