### ISSUE TITLE
Don't open OSC listening port on non-local interfaces without express user intent

### ISSUE THREAD

**Issue by ivxvm** [Dewb/monome-rack#196]
After I install monome collection the first time I added some monome modules to patch (grid and teletype) I got this windows 10 firewall warning window asking to trust public/whatever connection to the vcv rack. This didn't happen since I first installed vcv rack, so this is very suspicious. Do any of those modules connect to internet?

**Comment by Dewb** [comment]
These modules use OSC, a network protocol, to communicate with the serialosc server to provide device support for local and remote devices. This involves opening a listening port for messages from the device, so the Windows message is not unexpected.

**Comment by Dewb** [comment]
I'll leave this issue open because it should be possible in the future to only open this port on the local interface to avoid the firewall dialog. If people want to use devices attached to a remote host, there could be an explicit option to enable listening to ports on public interfaces.

**Comment by Dewb** [comment]
Fixed by #198.
