### ISSUE TITLE
Linux build

### ISSUE THREAD

**Issue by davephillips** [Dewb/monome-rack#2]
Linux Fedora 23
Rack 0.5.0

monome-rack builds cleanly on Linux and instantiates in Rack without trouble. Rack crashed when I deleted the virtual monome but I think it's an unrelated issue (Rack crashes occasionally with deleted modules). Since the current graphics are incomplete I have no clue what to do, I'll look up the specs for the White Whale sequencer and see if I can figure it out. Anyway, very cool project, thank you for the neat new modules. :)

**Comment by Dewb** [comment]
Thanks for trying it out, and thanks for the Linux report! Yeah, you'll definitely want to read the manual for the white whale module, adding the labels wouldn't help much.

https://monome.org/docs/modular/whitewhale/
