### ISSUE TITLE
segfault when disconnecting real grid

### ISSUE THREAD

**Issue by simonvanderveldt** [Dewb/monome-rack#31]
### What operating system and version are you running?
Linux

### What version of Rack are you running?
0.5.1

### What's the behavior you observed?
VCV Rack segfaults when a real grid is connected to White Whale (haven't tested the others) and you disconnect it.

### What should have happened instead?
VCV Rack shouldn't segfault ;)

If you want I can get a backtrace

**Comment by simonvanderveldt** [comment]
Sorry, just noticed #7 (searched for segfault but that word isn't in there :)). If you want to close this that's fine :)

**Comment by Dewb** [comment]
Yes, this is known and a fix is planned. Thanks for the report, it helps to know which issues are impacting people the most!

**Comment by Dewb** [comment]
This should be fixed in the 1.0 prerelease build.
