### ISSUE TITLE
Earthsea: crashing in different ways...

### ISSUE THREAD

**Issue by phdsg** [Dewb/monome-rack#32]
win7
rack 0.5

had a little time and tried to learn/play a bit with the earthsea module, but i'm having a hard time getting it to work with the virtual grids as well as grid64.

first of all:
it doesn't like the regular virtual grids! whenever i try to connect one my term gets spammed with 'e' letters.
with the monos it's a little bit better, but i had it crashing many times with certain key combinations.
still have to figure out the step-by-step clicks, but the last button i pressed was always the top left one.

trying some more and reporting back later.

**Comment by Dewb** [comment]
Sorry you experienced this! I've seen the 'e' spam issue before, and I thought I'd fixed it; are you using the latest master branch? What is the output of `git submodule status`?

**Comment by phdsg** [comment]
yup, all up date i think.

```
$ git pull
Already up to date.

```

```
$ git status
On branch master
Your branch is up to date with 'origin/master'.

```

```
$ git submodule status
 7cb767dee345db4ebdb637f4efa59c8e4692f9c5 firmware/earthsea (v1.9.4-2-g7cb767d)
 f50ca62af76ee2d6ef044baf39024c8abc194469 firmware/meadowphysics (v2.1-7-gf50ca62)
 f90ea318446d932b64c5564063d4fe61a571977c firmware/teletype (v2.1.0-141-gf90ea31)
 1c2074463d358bf863c7cfc7ef3873d787f2db15 firmware/whitewhale (v1.5-18-g1c20744)

```

**Comment by Dewb** [comment]
The `e` crash comes from code in libavr32 `setup_mext`, which is no longer called in the rewritten connection system (#7), and I haven't been able to make Earthsea crash in a while (as long as Rack is single-threaded mode, see #42.)

Is your grid64 hardware varibright or older series/40h? Unfortunately I've had to temporarily remove support for non-varibright hardware (see #44.)
