### ISSUE TITLE
Cannot compile!?

### ISSUE THREAD

**Issue by caecos** [Dewb/monome-rack#38]
MSYS2 - Windows 10 Pro

$ make
cd firmware && make -f whitewhale.mk
make[1] : on entre dans le répertoire « /home/caeco/rack/plugins/monome-rack/firmware »
whitewhale.mk:30: /arch.mk: No such file or directory
make[1]: *** Aucune règle pour fabriquer la cible « /arch.mk ». Arrêt.
make[1] : on quitte le répertoire « /home/caeco/rack/plugins/monome-rack/firmware »

**Comment by davephillips** [comment]
@caecos and @Dewb RACK_DIR is not being passed to the firmware mk files. An easy fix is to simply change this:

`include $(RACK_DIR)/arch.mk`

with this:

`include ../../../arch.mk`

HTH!

**Comment by Dewb** [comment]
@davephillips you are correct! @caecos, sorry for the oversight.

**Comment by Dewb** [comment]
new build instructions updated for the v1 branch.

**Comment by caecos** [comment]
Thank’s

Obtenez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : Michael Dewberry <notifications@github.com>
Envoyé : Tuesday, May 28, 2019 12:25:46 AM
À : Dewb/monome-rack
Cc : caecos; Mention
Objet : Re: [Dewb/monome-rack] Cannot compile!? (#38)


Closed #38<https://github.com/Dewb/monome-rack/issues/38>.
