### ISSUE TITLE
problem with instantiation in Rack

### ISSUE THREAD

**Issue by davephillips** [Dewb/monome-rack#4]
The plugin loads okay and the panels display properly (minus labels, of course), but looking at the command-line output I see this:

Binding to port 13000.
[warning] Creating new temporary firmware instance at module-firmware7kd6yQ
[warning] Failed to load library module-firmware7kd6yQ: module-firmware7kd6yQ: cannot open shared object file: No such file or directory

What's up with that ?

Cool project, btw. It has me thinking about purchasing a used monome.

**Comment by Dewb** [comment]
There's a new platform-specific submodule loader for the module firmware that I haven't had a chance to test on Linux yet. I'm installing a VM now to take a look, but in the meantime, you'll probably want to stick to this commit: https://github.com/Dewb/monome-rack/commit/aaed79253f7ef0057f2533396152918c436b9ef8

**Comment by davephillips** [comment]
Okay, thanks. I checked out the commit, build is good again.

**Comment by Dewb** [comment]
Head should build now. Thanks!

**Comment by davephillips** [comment]
All good now, thanks !

**Comment by Dewb** [comment]
BTW, yes, I highly recommend picking up a monome grid, it'll make this & future grid-based modules a lot more fun!
