### ISSUE TITLE
selecting CV A crashes Rack

### ISSUE THREAD

**Issue by davephillips** [Dewb/monome-rack#40]
Fedora 23 Linux
VCV Rack 0.6.2c from source

The subject line says it. Whenever I select any of the four buttons for CV A it reliably crashes Rack. CV B shows no such problem. No errors are reported at the terminal prompt, but I'll try to generate a debug report with gdb.

Btw, I've been playing with the White Whale and Meadowphysics modules, having great fun learning and using them. I'll post a YouTube video asap. Thank you for the cool plugin !

**Comment by Dewb** [comment]
Can you try this with the v1.0 beta and see if the issue still exists? If it does, can you describe your grid setup (virtual or one of the hardware models)?

**Comment by davephillips** [comment]
Hi Michael, Apologies for the delayed reply. I tested the latest Rack v1 pull with a fresh build from your repo, everything seems to work without complaint now. :)

**Comment by Dewb** [comment]
Fantastic!
