### ISSUE TITLE
Restore support for older-protocol grids (real and virtual)

### ISSUE THREAD

**Issue by Dewb** [Dewb/monome-rack#44]
The 0.6 branch supported both modern grids (mext protocol varibright) and older non-varibright models, but support for older protocols was somewhat tenuous since I don't have easy access to physical devices. The new connection system for 1.0 necessitated changing the way grid detection works, so this support has been removed until it can be reverified.

Separately, for the virtual grids, the new Rack library preview makes having separate varibright and series models in the library less desirable. The new plan is to have a single module per size, but add a right-click menu option to pick the protocol to emulate (and also the LED color?)

**Comment by CarlColglazier** [comment]
Current behavior seems to treat the 40h as half a 128. Is this expected?

**Comment by joopvdl** [comment]
I have an older non-varibright model. Happy to help out with testing etc
(of course, I am also missing support for it quite a lot)

Op wo 25 sep. 2019 om 17:05 schreef carl colglazier <
notifications@github.com>:

**Comment by joopvdl** [comment]
Don't want to sound pushy, but is there any chance we will get support for the older grids back?

**Comment by Dewb** [comment]
Apologies for the delay. Took the summer off from side projects (to get married!) and still catching up on the backlog. 

Chances will go up if I can get my hands on an older proto grid! Feel free to let me know if you see any cheap ones on reverb/lines/craigslist etc. Or just mail me one, lol.

**Comment by joopvdl** [comment]
First, congratulations!
Secondly: You could have borrowed mine, were there no ocean between us. But
for now, that's a bit impractical.
Are the differences between the boards that big? (Just curious)


Op ma 2 dec. 2019 om 01:12 schreef Michael Dewberry <
notifications@github.com>:

**Comment by Dewb** [comment]
Hello everyone still following this issue: support for older protocols has just been merged back into the plugin. I can test older protocols with the virtual grids, but for hardware I only have Mext-FTDI and Mext-CDC grids to test with (the latest two models) so I have no way to confirm whether 40h/Arduinome-FTDI or Series-FTDI function correctly.

I hope to have this support as part of the 1.0.0-alpha2 release. If you'd like to help test before then, you can download temporary prerelease builds here: https://github.com/Dewb/monome-rack/actions/runs/1276741052

If you're able to give me feedback on the behavior and performance with 40h/Series hardware, I'd greatly appreciate it! Apologies for this feature being out of a release for so long, thanks for sticking around.

**Comment by suit4** [comment]
I have a 40h/Arduinome-FTDI and can confirm that it is working an communication with the plugin.

The visualisation on the virtual grid looks different to that one  on the real grid, but I guess this is a side effect of the Arduinome not being able to display variable brightness. Those old grids are only capable of off and on.

**Comment by Dewb** [comment]
That's great news, thanks for the feedback!

By default, the virtual grids simulate the most recent varibright protocol. You can switch them into older protocols from the right-click menu. If you set a virtual grid to 40h protocol, does it match what you see on your hardware?

<img width="527" alt="image" src="https://user-images.githubusercontent.com/712405/135337451-723e608a-e6e0-4c5f-b99a-dc1ed3ce0c6c.png">

**Comment by suit4** [comment]
Huh? Is that part of the release package v1.0.0-alpha1?
Can't see that settings … do I have to compile from code first?

**Comment by Dewb** [comment]
The build I'd like you to test is linked in a comment above, sorry if that wasn't obvious -- it's in the Artifacts section here: https://github.com/Dewb/monome-rack/actions/runs/1276741052

**Comment by nay-seven** [comment]
I can also confirm a better result , no more flickering leds with an old  40h/Arduinome-FTDI ! 
Nice,  thanks a lot !

**Comment by joopvdl** [comment]
My 40h seems to function properly
Thank you for this!

**Comment by suit4** [comment]
Arduinome works perfectly, no flickering. Great job! Thank you, 
Me screaming: it's aliiiiiiiiiiiiveeeeee!!!

(Had to install the beta driver 1.4.7 for MacOS from https://ftdichip.com/drivers/vcp-drivers/ but that is Serialosc-FTDI-stuff)

**Comment by Dewb** [comment]
Thanks so much for the testing everyone! I'm in the process of sourcing my own 40h so I can more easily ensure support going forward.

The next alpha will include a bunch of additional grid performance improvements, if you want to check that those are also behaving correctly with the 40h, a new build is here: https://github.com/Dewb/monome-rack/actions/runs/1298997917

**Comment by joopvdl** [comment]
The biggest disadvantage of the 40h is you cannot reach the two keys top
right, so you cannot access those functions.
But that's probably also true with hardware.

**Comment by Dewb** [comment]
Yeah, not all of the modules support 8x8 grids fully in the main branch firmware. There's an issue to track that here: https://github.com/Dewb/monome-rack/issues/61

**Comment by Dewb** [comment]
I believe this has been solved, please let me know about any issues with older hardware!

**Comment by suit4** [comment]
Short update:
after OS upgrades, you might need to reinstall the FTDI driver.
Beta driver 1.4.7 for MacOS from https://ftdichip.com/drivers/vcp-drivers/
