### ISSUE TITLE
Build error "tt2020" branch [Win 10]

### ISSUE THREAD

**Issue by SteveRussell33** [Dewb/monome-rack#49]
output from make

cd firmware && make -f whitewhale.mk
make[1]: Entering directory '/c/_Projects/VCVRack/v1/Rack/plugins/monome-rack/firmware'
cc -DNULL=0 -o0 -D__AVR32_UC3B0256__ -fPIC -g -Werror=implicit-function-declaration -Imock_hardware -Imock_hardware/stubs -Iwhitewhale/libavr32/src -Iwhitewhale/libavr32/asf/common/services/usb -Iwhitewhale/libavr32/asf/common/services/usb/uhc -Iwhitewhale/libavr32/conf -Iwhitewhale/libavr32/conf/trilogy  -std=c99 -c -o ../build/firmware/whitewhale/src/main.c.o whitewhale/src/main.c
whitewhale/src/main.c: In function 'handler_PollADC':
whitewhale/src/main.c:655:14: warning: passing argument 1 of 'adc_convert' from incompatible pointer type [-Wincompatible-pointer-types]
  655 |  adc_convert(&adc);
      |              ^~~~
      |              |
      |              u16 (*)[4] {aka short unsigned int (*)[4]}
In file included from whitewhale/src/main.c:29:
mock_hardware/stubs/adc.h:4:23: note: expected 'u16 *' {aka 'short unsigned int *'} but argument is of type 'u16 (*)[4]' {aka 'short unsigned int (*)[4]'}
    4 | void adc_convert(u16* dst);
      |                  ~~~~~^~~
In file included from whitewhale/src/main.c:14:
whitewhale/src/main.c: At top level:
mock_hardware/stubs/print_funcs.h:13:46: warning: 'fprintf' is static but used in inline function 'print_dbg_hex' which is not static
   13 | inline void print_dbg_hex(unsigned long n) { fprintf(stderr, "%lx", n); }
      |                                              ^~~~~~~
mock_hardware/stubs/print_funcs.h:12:53: warning: 'fprintf' is static but used in inline function 'print_dbg_short_hex' which is not static
   12 | inline void print_dbg_short_hex(unsigned short n) { fprintf(stderr, "%d", n); }
      |                                                     ^~~~~~~
mock_hardware/stubs/print_funcs.h:11:51: warning: 'fprintf' is static but used in inline function 'print_dbg_char_hex' which is not static
   11 | inline void print_dbg_char_hex(unsigned char n) { fprintf(stderr, "%x", n); }
      |                                                   ^~~~~~~
mock_hardware/stubs/print_funcs.h:10:48: warning: 'fprintf' is static but used in inline function 'print_dbg_ulong' which is not static
   10 | inline void print_dbg_ulong(unsigned long n) { fprintf(stderr, "%ld", n); }
      |                                                ^~~~~~~
mock_hardware/stubs/print_funcs.h:9:37: warning: 'fprintf' is static but used in inline function 'print_dbg_char' which is not static
    9 | inline void print_dbg_char(int c) { fprintf(stderr, "%d", c); }
      |                                     ^~~~~~~
mock_hardware/stubs/print_funcs.h:8:42: warning: 'fprintf' is static but used in inline function 'print_dbg' which is not static
    8 | inline void print_dbg(const char* str) { fprintf(stderr, "%s", str); }
      |                                          ^~~~~~~
cc -DNULL=0 -o0 -D__AVR32_UC3B0256__ -fPIC -g -Werror=implicit-function-declaration -Imock_hardware -Imock_hardware/stubs -Iwhitewhale/libavr32/src -Iwhitewhale/libavr32/asf/common/services/usb -Iwhitewhale/libavr32/asf/common/services/usb/uhc -Iwhitewhale/libavr32/conf -Iwhitewhale/libavr32/conf/trilogy  -std=c99 -c -o ../build/firmware/whitewhale/libavr32/src/events.c.o whitewhale/libavr32/src/events.c
In file included from whitewhale/libavr32/src/events.c:10:
mock_hardware/stubs/print_funcs.h:13:46: warning: 'fprintf' is static but used in inline function 'print_dbg_hex' which is not static
   13 | inline void print_dbg_hex(unsigned long n) { fprintf(stderr, "%lx", n); }
      |                                              ^~~~~~~
mock_hardware/stubs/print_funcs.h:12:53: warning: 'fprintf' is static but used in inline function 'print_dbg_short_hex' which is not static
   12 | inline void print_dbg_short_hex(unsigned short n) { fprintf(stderr, "%d", n); }
      |                                                     ^~~~~~~
mock_hardware/stubs/print_funcs.h:11:51: warning: 'fprintf' is static but used in inline function 'print_dbg_char_hex' which is not static
   11 | inline void print_dbg_char_hex(unsigned char n) { fprintf(stderr, "%x", n); }
      |                                                   ^~~~~~~
mock_hardware/stubs/print_funcs.h:10:48: warning: 'fprintf' is static but used in inline function 'print_dbg_ulong' which is not static
   10 | inline void print_dbg_ulong(unsigned long n) { fprintf(stderr, "%ld", n); }
      |                                                ^~~~~~~
mock_hardware/stubs/print_funcs.h:9:37: warning: 'fprintf' is static but used in inline function 'print_dbg_char' which is not static
    9 | inline void print_dbg_char(int c) { fprintf(stderr, "%d", c); }
      |                                     ^~~~~~~
mock_hardware/stubs/print_funcs.h:8:42: warning: 'fprintf' is static but used in inline function 'print_dbg' which is not static
    8 | inline void print_dbg(const char* str) { fprintf(stderr, "%s", str); }
      |                                          ^~~~~~~
cc -DNULL=0 -o0 -D__AVR32_UC3B0256__ -fPIC -g -Werror=implicit-function-declaration -Imock_hardware -Imock_hardware/stubs -Iwhitewhale/libavr32/src -Iwhitewhale/libavr32/asf/common/services/usb -Iwhitewhale/libavr32/asf/common/services/usb/uhc -Iwhitewhale/libavr32/conf -Iwhitewhale/libavr32/conf/trilogy  -std=c99 -c -o ../build/firmware/whitewhale/libavr32/src/timers.c.o whitewhale/libavr32/src/timers.c
In file included from whitewhale/libavr32/src/timers.c:1:
mock_hardware/stubs/print_funcs.h:13:46: warning: 'fprintf' is static but used in inline function 'print_dbg_hex' which is not static
   13 | inline void print_dbg_hex(unsigned long n) { fprintf(stderr, "%lx", n); }
      |                                              ^~~~~~~
mock_hardware/stubs/print_funcs.h:12:53: warning: 'fprintf' is static but used in inline function 'print_dbg_short_hex' which is not static
   12 | inline void print_dbg_short_hex(unsigned short n) { fprintf(stderr, "%d", n); }
      |                                                     ^~~~~~~
mock_hardware/stubs/print_funcs.h:11:51: warning: 'fprintf' is static but used in inline function 'print_dbg_char_hex' which is not static
   11 | inline void print_dbg_char_hex(unsigned char n) { fprintf(stderr, "%x", n); }
      |                                                   ^~~~~~~
mock_hardware/stubs/print_funcs.h:10:48: warning: 'fprintf' is static but used in inline function 'print_dbg_ulong' which is not static
   10 | inline void print_dbg_ulong(unsigned long n) { fprintf(stderr, "%ld", n); }
      |                                                ^~~~~~~
mock_hardware/stubs/print_funcs.h:9:37: warning: 'fprintf' is static but used in inline function 'print_dbg_char' which is not static
    9 | inline void print_dbg_char(int c) { fprintf(stderr, "%d", c); }
      |                                     ^~~~~~~
mock_hardware/stubs/print_funcs.h:8:42: warning: 'fprintf' is static but used in inline function 'print_dbg' which is not static
    8 | inline void print_dbg(const char* str) { fprintf(stderr, "%s", str); }
      |                                          ^~~~~~~
cc -DNULL=0 -o0 -D__AVR32_UC3B0256__ -fPIC -g -Werror=implicit-function-declaration -Imock_hardware -Imock_hardware/stubs -Iwhitewhale/libavr32/src -Iwhitewhale/libavr32/asf/common/services/usb -Iwhitewhale/libavr32/asf/common/services/usb/uhc -Iwhitewhale/libavr32/conf -Iwhitewhale/libavr32/conf/trilogy  -std=c99 -c -o ../build/firmware/whitewhale/libavr32/src/util.c.o whitewhale/libavr32/src/util.c
cc -DNULL=0 -o0 -D__AVR32_UC3B0256__ -fPIC -g -Werror=implicit-function-declaration -Imock_hardware -Imock_hardware/stubs -Iwhitewhale/libavr32/src -Iwhitewhale/libavr32/asf/common/services/usb -Iwhitewhale/libavr32/asf/common/services/usb/uhc -Iwhitewhale/libavr32/conf -Iwhitewhale/libavr32/conf/trilogy  -std=c99 -c -o ../build/firmware/mock_hardware/adapter.c.o mock_hardware/adapter.c
mock_hardware/adapter.c: In function 'ftdi_read':
mock_hardware/adapter.c:238:67: warning: passing argument 3 of 'hardware_readSerial_internal' from incompatible pointer type [-Wincompatible-pointer-types]
  238 |     hardware_readSerial_internal(FTDI_BUS, &current_ftdi_message, &current_ftdi_message_length);
      |                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                   |
      |                                                                   u8 * {aka unsigned char *}
In file included from mock_hardware/adapter.c:2:
mock_hardware/mock_hardware.h:33:79: note: expected 'uint32_t *' {aka 'unsigned int *'} but argument is of type 'u8 *' {aka 'unsigned char *'}
   33 | void hardware_readSerial_internal(serial_bus_t bus, uint8_t** pbuf, uint32_t* pcount);
      |                                                                     ~~~~~~~~~~^~~~~~
mock_hardware/adapter.c: In function 'screen_clear':
mock_hardware/adapter.c:352:39: warning: passing argument 2 of 'hardware_getScreenBuffer' makes pointer from integer without a cast [-Wint-conversion]
  352 |     hardware_getScreenBuffer(&screen, width, height);
      |                                       ^~~~~
      |                                       |
      |                                       uint16_t {aka short unsigned int}
In file included from mock_hardware/adapter.c:2:
mock_hardware/mock_hardware.h:38:56: note: expected 'uint16_t *' {aka 'short unsigned int *'} but argument is of type 'uint16_t' {aka 'short unsigned int'}
   38 | void hardware_getScreenBuffer(uint8_t** ptr, uint16_t* width, uint16_t* height);
      |                                              ~~~~~~~~~~^~~~~
mock_hardware/adapter.c:352:46: warning: passing argument 3 of 'hardware_getScreenBuffer' makes pointer from integer without a cast [-Wint-conversion]
  352 |     hardware_getScreenBuffer(&screen, width, height);
      |                                              ^~~~~~
      |                                              |
      |                                              uint16_t {aka short unsigned int}
In file included from mock_hardware/adapter.c:2:
mock_hardware/mock_hardware.h:38:73: note: expected 'uint16_t *' {aka 'short unsigned int *'} but argument is of type 'uint16_t' {aka 'short unsigned int'}
   38 | void hardware_getScreenBuffer(uint8_t** ptr, uint16_t* width, uint16_t* height);
      |                                                               ~~~~~~~~~~^~~~~~
cc -DNULL=0 -o0 -D__AVR32_UC3B0256__ -fPIC -g -Werror=implicit-function-declaration -Imock_hardware -Imock_hardware/stubs -Iwhitewhale/libavr32/src -Iwhitewhale/libavr32/asf/common/services/usb -Iwhitewhale/libavr32/asf/common/services/usb/uhc -Iwhitewhale/libavr32/conf -Iwhitewhale/libavr32/conf/trilogy  -std=c99 -c -o ../build/firmware/mock_hardware/mock_hardware.c.o mock_hardware/mock_hardware.c
mock_hardware/mock_hardware.c: In function 'hardware_declareNVRAM':
mock_hardware/mock_hardware.c:330:15: warning: assignment discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
  330 |     nvram_ptr = ptr;
      |               ^
mock_hardware/mock_hardware.c: In function 'hardware_declareVRAM':
mock_hardware/mock_hardware.c:347:14: warning: assignment discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
  347 |     vram_ptr = ptr;
      |              ^
cc -DNULL=0 -o0 -D__AVR32_UC3B0256__ -fPIC -g -Werror=implicit-function-declaration -Imock_hardware -Imock_hardware/stubs -Iwhitewhale/libavr32/src -Iwhitewhale/libavr32/asf/common/services/usb -Iwhitewhale/libavr32/asf/common/services/usb/uhc -Iwhitewhale/libavr32/conf -Iwhitewhale/libavr32/conf/trilogy  -std=c99 -c -o ../build/firmware/mock_hardware/monome.c.o mock_hardware/monome.c
In file included from mock_hardware/monome.c:2:
mock_hardware/stubs/print_funcs.h:13:46: warning: 'fprintf' is static but used in inline function 'print_dbg_hex' which is not static
   13 | inline void print_dbg_hex(unsigned long n) { fprintf(stderr, "%lx", n); }
      |                                              ^~~~~~~
mock_hardware/stubs/print_funcs.h:12:53: warning: 'fprintf' is static but used in inline function 'print_dbg_short_hex' which is not static
   12 | inline void print_dbg_short_hex(unsigned short n) { fprintf(stderr, "%d", n); }
      |                                                     ^~~~~~~
mock_hardware/stubs/print_funcs.h:11:51: warning: 'fprintf' is static but used in inline function 'print_dbg_char_hex' which is not static
   11 | inline void print_dbg_char_hex(unsigned char n) { fprintf(stderr, "%x", n); }
      |                                                   ^~~~~~~
mock_hardware/stubs/print_funcs.h:10:48: warning: 'fprintf' is static but used in inline function 'print_dbg_ulong' which is not static
   10 | inline void print_dbg_ulong(unsigned long n) { fprintf(stderr, "%ld", n); }
      |                                                ^~~~~~~
mock_hardware/stubs/print_funcs.h:9:37: warning: 'fprintf' is static but used in inline function 'print_dbg_char' which is not static
    9 | inline void print_dbg_char(int c) { fprintf(stderr, "%d", c); }
      |                                     ^~~~~~~
mock_hardware/stubs/print_funcs.h:8:42: warning: 'fprintf' is static but used in inline function 'print_dbg' which is not static
    8 | inline void print_dbg(const char* str) { fprintf(stderr, "%s", str); }
      |                                          ^~~~~~~
g++ -o ../res/firmware/whitewhale.dll ../build/firmware/whitewhale/src/main.c.o ../build/firmware/whitewhale/libavr32/src/events.c.o ../build/firmware/whitewhale/libavr32/src/timers.c.o ../build/firmware/whitewhale/libavr32/src/util.c.o ../build/firmware/mock_hardware/adapter.c.o ../build/firmware/mock_hardware/mock_hardware.c.o ../build/firmware/mock_hardware/monome.c.o -shared
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../build/firmware/mock_hardware/adapter.c.o:C:\_Projects\VCVRack\v1\Rack\plugins\monome-rack\firmware/mock_hardware/adapter.c:28: multiple definition of `tcTicks'; ../build/firmware/whitewhale/src/main.c.o:C:\_Projects\VCVRack\v1\Rack\plugins\monome-rack\firmware/whitewhale/libavr32/src/init_trilogy.h:7: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../build/firmware/mock_hardware/adapter.c.o:C:\_Projects\VCVRack\v1\Rack\plugins\monome-rack\firmware/mock_hardware/adapter.c:29: multiple definition of `tcOverflow'; ../build/firmware/whitewhale/src/main.c.o:C:\_Projects\VCVRack\v1\Rack\plugins\monome-rack\firmware/whitewhale/libavr32/src/init_trilogy.h:8: first defined here
collect2.exe: error: ld returned 1 exit status
make[1]: *** [whitewhale.mk:56: ../res/firmware/whitewhale.dll] Error 1
make[1]: Leaving directory '/c/_Projects/VCVRack/v1/Rack/plugins/monome-rack/firmware'
make: *** [Makefile:41: firmwares] Error 2

**Comment by Dewb** [comment]
This is an active development branch, I'm still getting it up and running on all platforms.

**Comment by cbix** [comment]
Similar issue here building v2.2.8 on Arch Linux using GCC 14. makepkg adds some extra flags here but even without these (`make firmware-build`) I'm getting the error.
```
cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection         -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -g -ffile-prefix-map=/home/florian/build/archlinux-proaudio/packages/vcvrack-monome/src=/usr/src/debug/vcvrack-monome -flto=auto  -Isrc -Isrc/common -Isrc/common/core -Isrc/common/util -Isrc/common/widgets -Isrc/common/core/GridConnection -Isrc/virtualgrid -Isrc/whitewhale -Isrc/meadowphysics -Isrc/earthsea -Isrc/teletype -Isrc/ansible -Isrc/faderbank -Ilib/base64 -Ilib/oscpack -Ilib/serialosc -Ilib/simple-svg -Ifirmware/mock_hardware -g  -fPIC -I/usr/share/vcvrack/include -I/usr/share/vcvrack/dep/include -fno-gnu-unique -I/usr/include/vcvrack -I/usr/include/vcvrack/dep -I/usr/include/nanosvg -MMD -MP -g -O3 -funsafe-math-optimizations -fno-omit-frame-pointer -Wall -Wextra -Wno-unused-parameter -march=nehalem  -std=c99  -D__AVR32_UC3B0256__ -Imock_hardware -Imock_hardware/include -Iwhitewhale/libavr32/src -Iwhitewhale/libavr32/src/usb/midi -Iwhitewhale/libavr32/src/usb/hid -Iwhitewhale/libavr32/src/usb/cdc -Iwhitewhale/libavr32/asf/common/services/usb -Iwhitewhale/libavr32/asf/common/services/usb/uhc -Iwhitewhale/libavr32/conf -Iwhitewhale/libavr32/conf/trilogy  -DGIT_VERSION="\"v1.5 6CD668C\"" -DDEBUG -DNULL=0 -DARCH_AVR32=1 -fPIC -fvisibility=hidden -g -Werror=implicit-function-declaration -I../lib/cbbq  -MMD -MP -g -O3 -funsafe-math-optimizations -fno-omit-frame-pointer -Wall -Wextra -Wno-unused-parameter -DARCH_X64 -march=nehalem -DARCH_LIN  -c -o ../build/firmware/whitewhale/whitewhale/src/main.c.o whitewhale/src/main.c
In file included from whitewhale/libavr32/src/monome.h:5,
                 from whitewhale/src/main.c:27:
mock_hardware/include/ftdi.h:16:1: warning: type qualifiers ignored on function return type [-Wignored-qualifiers]
   16 | volatile u8 ftdi_rx_bytes(void);
      | ^~~~~~~~
[...]
whitewhale/src/main.c: In function ‘handler_PollADC’:
whitewhale/src/main.c:660:21: error: passing argument 1 of ‘adc_convert’ from incompatible pointer type [-Wincompatible-pointer-types]
  660 |         adc_convert(&adc);
      |                     ^~~~
      |                     |
      |                     u16 (*)[4] {aka short unsigned int (*)[4]}
In file included from whitewhale/src/main.c:29:
mock_hardware/include/adc.h:4:22: note: expected ‘u16 *’ {aka ‘short unsigned int *’} but argument is of type ‘u16 (*)[4]’ {aka ‘short unsigned int (*)[4]’}
    4 | void adc_convert(u16 dst[4]);
      |                  ~~~~^~~~~~
whitewhale/src/main.c: In function ‘handler_MonomeGridKey’:
whitewhale/src/main.c:1175:104: warning: comparison is always true due to limited range of data type [-Wtype-limits]
 1175 |                                               else if((y == 5 || y == 6) && z && x<4 && edit_cv_step != -1) {
      |                                                                                                      ^~

make[1]: *** [compile.mk:86: ../build/firmware/whitewhale/whitewhale/src/main.c.o] Error 1
make[1]: Leaving directory '/home/florian/build/archlinux-proaudio/packages/vcvrack-monome/src/monome-rack/firmware'
make: *** [Makefile:62: firmware-build] Error 2
```
