### ISSUE TITLE
Teletype param range is wrong.

### ISSUE THREAD

**Issue by jpnielsen** [Dewb/monome-rack#53]
### What's the behavior you observed?
"Param" goes from 0 to 16380 - The middle and default is 8188
"IN" 10V is 16380 

### What should have happened instead?

It should be like the hardware.
0V is 0, 5V is 8192, 10 V is 16384

"the range is 0-16384, the same as how 0-10v is represented"
https://monome.org/docs/teletype/studies-4/

**Comment by Dewb** [comment]
Good catch, thanks!
