### ISSUE TITLE
Add virtual faderbank module

### ISSUE THREAD

**Issue by Dewb** [Dewb/monome-rack#64]
Requires i2c.

**Comment by jpnielsen** [comment]
Hope to see this module in VCV Rack 2 soon ! 

I recently bought a faderbank derivative:
https://atovproject.de/manuals/16nrework

**Comment by Dewb** [comment]
It's fully prototyped! It just awaits a good simulated i2c solution so multiple faderbanks/multiple teletypes can be supported reasonably.

**Comment by jpnielsen** [comment]
Don't know of any other modules that attemps something like that - except perhaps

"Most Virtue expander modules support the vMIDI™ protocol developed by Kilpatrick Audio. This allows MIDI to be patched between modules as easily as patching CV."

https://github.com/kilpatrickaudio/Kilpatrick-Toolbox

Maybe something you can reuse in there ?

**Comment by Dewb** [comment]
That’s addressing a different set of problems. The tricky bit with i2c is that in real hardware, it involves sending a query and waiting on response. Two separate digital modules have their own independent CPUs. But Rack modules might be running sequentially on the same thread and can’t block on each other. I have a solution in mind, I just need to find the time to execute it.

**Comment by Dewb** [comment]
If you’re eager to see something, here is a picture of the 16n prototype module: 
![](https://media.discordapp.net/attachments/850955610471661610/879774577708916786/unknown.png)

**Comment by Dewb** [comment]
Implemented in 2.2.0!
