### ISSUE TITLE
Invalid module tags in plugin.json

### ISSUE THREAD

**Issue by cschol** [Dewb/monome-rack#70]
I know this is a WIP, but I ran it through the library integration process and encountered the following issues:

```
[monome-rack] Validating plugin.json...FAILED
[monome-rack] Issues found in `plugin.json`:
whitewhale: invalid module tags: sequencer, clock, digital, hardware clone, external
earthsea: invalid module tags: sequencer, digital, hardware clone, external
meadowphysics: invalid module tags: sequencer, clock, digital, hardware clone, external
teletype: invalid module tags: sequencer, clock, logic, function generator, digital, hardware clone, external
grid128: invalid module tags: controller
grid64: invalid module tags: controller
grid256: invalid module tags: controller
--Valid tags are defined in https://raw.githubusercontent.com/VCVRack/Rack/v1/src/tag.cpp
```

**Comment by Dewb** [comment]
I see “clock” should be replaced with “clock generator” or “clock modulator”, but the rest of those tags look legal according to https://vcvrack.com/manual/Manifest#modules-tags. Is there a new list of legal tags for v2?

**Comment by cschol** [comment]
I think the tags need to be capitalized. They will be lower-case matched within Rack.

**Comment by Dewb** [comment]
The docs say case doesn't matter:
> All tags must match the following strings, case-insensitive.

Not sure why earthsea and meadowphysics aren't also flagged, since they use some of the same tags. Do you have a link to the validation script?
