### ISSUE TITLE
Teletype knob and param values are not correct.

### ISSUE THREAD

**Issue by jpnielsen** [Dewb/monome-rack#72]
Teletype 
knob max is 16383
param = "16380"
both should be 16384 ?

IN max = 16384 is OK

**Comment by Dewb** [comment]
Thanks for the report! `16383` is the correct default maximum value for both, so `IN` is wrong. By "param = 16380", do you mean the tooltip, meaning you're testing the v2 build?

**Comment by Dewb** [comment]
`IN` and `PARAM` are now both 0-16383 (in the main branch.) Tooltips still need to be adjusted in v2.
