### ISSUE TITLE
Teletype not responding (Rack v2 dev)

### ISSUE THREAD

**Issue by davephillips** [Dewb/monome-rack#73]
Linux 4.15.0-147-lowlatency #151-Ubuntu SMP PREEMPT x86_64
Ubuntu 18.04
VCV Rack CE v2.git.420e781f

In the latest pull Teletype is unresponsive with my build of Rack v2. This script:

X RRAND 30 50
CV 1 N X
TR.P 1

works without error in Rack v1. In Rack v2 the input indicates reception of a trigger but nothing is coming through the CV and TR output ports.

No error is reported. I tried reloading the firmware during a session but got no joy. :(

I've attached a screenshot of the patch. This editor won't accept the patch format itself.

![tt-test-simple](https://user-images.githubusercontent.com/7815938/137335704-3f8f3fce-49d7-4f11-aa29-212d20f4519c.png)

**Comment by Dewb** [comment]
When you say Teletype is unresponsive, you mean the outputs are unresponsive, but the screen/interactive features still work?
