### ISSUE TITLE
Rightclick param knob, the value is always 0

### ISSUE THREAD

**Issue by jpnielsen** [Dewb/monome-rack#77]
latest build for Rack 2.git.219bbaf1

![image](https://user-images.githubusercontent.com/27916597/139622272-721a25e4-aae9-435a-aca2-756221e4e6de.png)

When I right-click the param knob, the value always shows 0
If I enter any value in the input box after right-clicking the param knob, the PARAM value is always 0

Turning the param knob works, and gives PARAM values as expected.

**Comment by Dewb** [comment]
Thanks, good catch! Should be fixed in https://github.com/Dewb/monome-rack/actions/runs/1407946321
