### ISSUE TITLE
License clarification needed

### ISSUE THREAD

**Issue by falkTX** [Dewb/monome-rack#86]
Hi there, this is a quick question.
Is the license of this project `gpl2.0-only` or `gpl2.0-or-later` ?
The distinction is quite important, one allows to use and merge other GPLv3 licensed code, the other does not.
GPLv2.0 is also not compatible with EUPL.

And perhaps more importantly, only GPLv3 was declared compatible with CC-BY-SA, GPLv2 has not.
See https://creativecommons.org/share-your-work/licensing-considerations/compatible-licenses/

**Comment by Dewb** [comment]
Current license is GPL-2.0-only, as spec’d in the `LICENSE` and in the license files of the other projects brought in as git submodules under `/firmware`.

Is this about the Cardinal project? If so, I’m broadly supportive of your goals and I looked into it a little bit last fall but I got the impression the dynamic linking this plug-in does would be a bigger obstacle than the license.

**Comment by falkTX** [comment]
> Current license is GPL-2.0-only, as spec’d in the `LICENSE` and in the license files of the other projects brought in as git submodules under `/firmware`.

It is not actually known if work created under CC-BY-SA (the firmware) can be used with other GPLv2 licensed code.
The investigation in https://wiki.creativecommons.org/wiki/ShareAlike_compatibility:_GPLv3 only relates to GPLv3. I could not find any resources related to GPLv2.

> Is this about the Cardinal project? If so, I’m broadly supportive of your goals and I looked into it a little bit last fall but I got the impression the dynamic linking this plug-in does would be a bigger obstacle than the license.

It is not related, I just saw a licensing issue here. For Cardinal everything is built-in, it doesn't load external modules, but doesn't matter.
The use of CC-BY-SA code mixed with GPL does not allow for the "or plus" clause, so it will never be part of Cardinal anyway.

**Comment by falkTX** [comment]
Maybe I misunderstood. There is no single code in use (by the dependencies) that is CC-BY-SA licensed?
If not, then all is good.

But please correct `plugin.json` license field as "GPL-2.0" as written there is not a valid SPDX identifier.
See https://spdx.org/licenses/ for a reasonable size list of licenses.

Now off topic to all this, using "GPLv2-only" is quite sad to see. It prevents the work from being combined with MPL, GPLv3, EUPL and many other licenses. Even "GPLv3-only" is problematic if we think about the long term.

**Comment by mxmilkiib** [comment]
It is to do with Cardinal, someone on linuxmusicians.com was wondering if this module could be included in it.

But yes I guess there a big problem because of the dependency licenses. (Personally I don't get the point of not using the + licence versions, given the hassle caused down the line by not doing so)

**Comment by falkTX** [comment]
> It is to do with Cardinal, someone on linuxmusicians.com was wondering if this module could be included in it.

license issues in general dont have to do with cardinal.
my attention to this repo was brought because of cardinal sure, but then I saw some little things that needed clarification which do not relate to cardinal.

**Comment by Dewb** [comment]
Ah, yes, the SPDX identifier is indeed invalid, thanks. I'll fix that.

I am constrained by the licenses of the other submodules here. I'm in general skeptical of the "or any later version" licensing. I *could* investigate relicensing everything, but I'd need to hear a pitch on why. If this is about Cardinal, like I said, I would be supportive of that in general, but this plugin by design loads additional dynamic libraries (one per module instance) at runtime, and I had the impression that was disallowed in Cardinal.

**Comment by Dewb** [comment]
Hey, sorry, I didn’t mean to inspire you to write a long treatise about licensing. I understand the pros and cons of GPL2/3 and +/-. I was asking *what outcome are you trying to enable*. General principles aside, why is the license of *this* repo something you’re concerned about?

**Comment by falkTX** [comment]
hmm I am not particularly. just had to deal with licensing stuff recently, saw this one mentioned and come to say a few things.
there is no specific reason needed for helping others.

**Comment by Dewb** [comment]
Ok, understood. Thanks for the heads up about the invalid SPDX string, I've fixed it.
