### ISSUE TITLE
Support more grids

### ISSUE THREAD

**Issue by Dewb** [Dewb/monome-rack#9]
Currently, only modern varibright grid 128 models are supported, for both virtual and real grids. (A real varibright 256 will work, but will only use the top half.) 

Rough order of priorities:
- [x] Virtual 64
- [ ] Identify real 64/256 correctly
- [ ] Identify real non-varibright/older protocol models correctly
- [x] Virtual non-varibright/older protocol models (for testing)
- [ ] Virtual 256
- [ ] Virtual 512??? (probably not... but what if there was a [plane](https://www.youtube.com/watch?v=OfFyvh_BGN8) port?)

**Comment by phdsg** [comment]
oh yes, please.
when i saw this module released, i picked up ancient grid64 from a friend who didn't use it.
and it works.
kinda.
no lights and i can only access what's on the left 64 buttons of the 128, but i can use the virtual 128 to get to the rest.
this is already great fun to play with.
thx for this.

**Comment by Dewb** [comment]
Nice, glad it's (kinda) working! You could probably get the older-protocol grid to light up by changing the call to `sendDeviceLedLevelMapCommand` [here](https://github.com/Dewb/monome-rack/blob/master/src/common/monomemodulebase.cpp#L60) to a loop of calls to `sendDeviceLedCommand`. Since the white whale stock firmware only supports the 128, a 64 is going to be frustrating no matter what, but some of the other firmwares and other modules will have better support for 64s, iirc.

**Comment by phdsg** [comment]
what's also very neat is that i can have virtual grid selected in whitewhale and still use the hardware to control (the left side) stuff and see what lights should be on.

i'll try the led change later today and report back.

**Comment by phdsg** [comment]
i'm not a (good enough) programmer, so i couldn't figure out the led part.
only could get the top left one to light up.
still, so much fun. got it now set up to be an 8 stepper with 8 patterns.
can jam on all 4 triggers and one cv without the virtual grid (which can be a bit of a resource eater on my machine).
thx again.

**Comment by Dewb** [comment]
So I was wrong, WW totally supports the 64, it will switch to an 8-step mode. See this video for a demo on the hardware:

https://vimeo.com/104940985

To make this work in VCVrack, I need to pass the identification info from the hardware grid to the software module. I will try and prototype this sometime this weekend, if you’re willing to build it and give it a try. I unfortunately only have a varibright 256 for testing myself.

**Comment by phdsg** [comment]
oh definitely. can't wait.
the 64 i got is really old. one of the first i think.

**Comment by Dewb** [comment]
Working on 64 support again tonight! Getting close.

**Comment by phdsg** [comment]
saw the commits and i'm already building. thank you.
anything specific you want to have checked?

**Comment by Dewb** [comment]
The recent changes should allow you to connect to your hardware 64 grid and have white whale automatically switch into 8-step mode. Your grid still won’t light up, I need to make one more change to the serialosc code, probably tonight.

**Comment by phdsg** [comment]
didn't have much time last week. 
had a little ww session with a virtual64 and my hardware.
works as expected so far.
well done. super fun!
really looking forward to this thing blinking at me.

**Comment by Dewb** [comment]
Awesome! I think I have the backwards compatible protocol LED messages to older hardware working now, but I didn’t check it in last night because the virtual grids are broken. If I can’t fix that soon I’ll check the hardware changes into a branch for you to try out.

**Comment by Dewb** [comment]
Full support for all models of 64 and 128 are in!

**Comment by phdsg** [comment]
yeah i saw the commits and checked again [here](https://monome.org/docs/editions/) to be sure what i really have and it seems to be one of the "series" and the device id i see in the ww menu matches the one i see in other grid-apps: m64-527 monome 64)
![monomerack_ww_64grid](https://user-images.githubusercontent.com/33329578/34070064-abef063e-e25e-11e7-9296-18308e0a7c1f.PNG)

but nothing seems to have changed from what i checked in a short session. did i miss something?

**Comment by Dewb** [comment]
Cool, yep, that ID suggests a “series” model. So when you plug it in, you can control the module, but you see no lights on the device? Hmm. I have a theory, will push some changes for you to try. Thanks again for testing!

**Comment by Dewb** [comment]
Okay, now that I've had breakfast, yep, I was doing a dumb thing and sending /grid/led/level/map instead of /grid/led/map to series devices. Was too focused on the 40h code last night. Try it now!

**Comment by phdsg** [comment]
holy shit, you did it. awesome stuff. blinkediblink.  now i gotta dig into the manual(s) of the module(s) again and try all the functions properly.

**Comment by phdsg** [comment]
also noticed that this edition has a tilt sensor. can this be used for anything in the module?

**Comment by Dewb** [comment]
Hooray! Have fun :)

No, I don’t believe these three modules currently do anything with the tilt sensor.

**Comment by Dewb** [comment]
Moving 256-related tasks to a separate issue.
